server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 60000  # wait 60 seconds before failing
      connectionTimeout: 10000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


springdoc:
  swagger-ui:
    operationsSorter: method
    defaultModelsExpandDepth: -1

management:
  endpoints:
    web:
      exposure:
        include: "*"

#  springdoc.packagesToScan=package1, package2
#  springdoc.pathsToMatch=/v1, /api/balance/**
